%define debug_package %{nil}

Name:           draco-base
Version:        1.0
Release:        4.draco1
Summary:        Linux Core System
Group:          System Environment/Base
License:        GPLv2
Provides:	draco-base

BuildArch:noarch
Requires:rcd
Requires:bmake
Requires:bmake-mk
Requires:draco-release
Requires:pkgin
Requires:pkg_install
Requires:tnftp
Requires:acl
Requires:attr
Requires:audit
Requires:audit
Requires:authconfig
Requires:basesystem
Requires:bash
Requires:bc
Requires:binutils
Requires:bzip2
Requires:bzip2
Requires:ca-certificates
Requires:checkpolicy
Requires:chkconfig
Requires:coreutils
Requires:coreutils-libs
Requires:cpio
Requires:cracklib
Requires:cracklib-dicts
Requires:crda
Requires:curl
Requires:cyrus-sasl-lib
Requires:dash
Requires:db4
Requires:db4-utils
Requires:dbus-glib
Requires:dbus-libs
Requires:device-mapper
Requires:device-mapper-event
Requires:device-mapper-event-libs
Requires:device-mapper-libs
Requires:device-mapper-persistent-data
Requires:dhclient
Requires:dhcp-common
Requires:diffutils
Requires:dracut
Requires:dracut-kernel
Requires:e2fsprogs
Requires:e2fsprogs-libs
Requires:efibootmgr
Requires:elfutils-libelf
Requires:ethtool
Requires:expat
Requires:file
Requires:file-libs
Requires:filesystem
Requires:findutils
Requires:fipscheck
Requires:fipscheck-lib
Requires:gamin
Requires:gawk
Requires:gdbm
Requires:glib2
Requires:glibc
Requires:glibc-common
Requires:gmp
Requires:gnupg2
Requires:gpgme
Requires:grep
Requires:groff
Requires:grub
Requires:grubby
Requires:gzip
Requires:hwdata
Requires:info
Requires:initscripts
Requires:iproute
Requires:iptables
Requires:iptables-ipv6
Requires:iputils
Requires:iw
Requires:kbd
Requires:kbd-misc
Requires:kernel
Requires:kernel-firmware
Requires:keyutils-libs
Requires:krb5-libs
Requires:less
Requires:libacl
Requires:libarchive
Requires:libattr
Requires:libblkid
Requires:libcap
Requires:libcap-ng
Requires:libcom_err
Requires:libcurl
Requires:libdrm
Requires:libedit
Requires:libffi
Requires:libgcc
Requires:libgcrypt
Requires:libgpg-error
Requires:libidn
Requires:libnih
Requires:libnl
Requires:libpciaccess
Requires:libselinux
Requires:libselinux-utils
Requires:libsemanage
Requires:libsepol
Requires:libss
Requires:libssh2
Requires:libstdc++
Requires:libtasn1
Requires:libudev
Requires:libusb
Requires:libuser
Requires:libutempter
Requires:libuuid
Requires:libxml2
Requires:logrotate
Requires:lua
Requires:lvm2
Requires:lvm2-libs
Requires:m4
Requires:make
Requires:MAKEDEV
Requires:mingetty
Requires:mlocate
Requires:module-init-tools
Requires:ncurses
Requires:ncurses-base
Requires:ncurses-libs
Requires:net-tools
Requires:newt
Requires:newt-python
Requires:nspr
Requires:nss
Requires:nss-softokn
Requires:nss-softokn-freebl
Requires:nss-sysinit
Requires:nss-tools
Requires:nss-util
Requires:ntpdate
Requires:openldap
Requires:openssl
Requires:p11-kit
Requires:p11-kit-trust
Requires:pam
Requires:passwd
Requires:pciutils-libs
Requires:pcre
Requires:pinentry
Requires:pkgconfig
Requires:plymouth
Requires:plymouth-core-libs
Requires:plymouth-scripts
Requires:policycoreutils
Requires:popt
Requires:procps
Requires:psmisc
Requires:pth
Requires:pygpgme
Requires:python
Requires:python
Requires:python-libs
Requires:python-pycurl
Requires:python-urlgrabber
Requires:readline
Requires:rootfiles
Requires:rpm
Requires:rpm-libs
Requires:rpm-python
Requires:rsyslog
Requires:sed
Requires:selinux-policy
Requires:selinux-policy-targeted
Requires:setup
Requires:shadow-utils
Requires:shared-mime-info
Requires:slang
Requires:sqlite
Requires:sudo
Requires:system-config-firewall-base
Requires:sysvinit-tools
Requires:tar
Requires:tcp_wrappers-libs
Requires:tree
Requires:tzdata
Requires:udev
Requires:upstart
Requires:ustr
Requires:util-linux-ng
Requires:vim-minimal
Requires:which
Requires:wireless-tools
Requires:wpa_supplicant
Requires:xz
Requires:xz-libs
Requires:yum
Requires:yum-metadata-parser
Requires:yum-plugin-fastestmirror
Requires:zlib
#Requires:plymouth-theme-rings
Requires:pciutils
Requires:p7zip
Requires:openssh-clients
Requires:openssh-server

%description
Core Linux System

%build
echo OK

%files
%defattr(-,root,root)

%changelog
